version: '2'
output: 'prefixed'

tasks:
  proto:
    desc: Generates grpc code
    shell:
      - protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative proto/server.proto
